// examples/react/src/components/Editor.tsx
import { useEffect, useRef, forwardRef, useImperativeHandle } from 'react';
import EditorJS from 'editorjs';
import { Slabs } from '@slabs/client';

interface EditorProps {
  data?: any;
  onChange?: (data: any) => void;
}

export interface EditorRef {
  save: () => Promise<any>;
  clear: () => Promise<void>;
}

export const Editor = forwardRef<EditorRef, EditorProps>(({ data, onChange }, ref) => {
  const editorRef = useRef<EditorJS | null>(null);
  const holderRef = useRef<HTMLDivElement>(null);
  const isInitialized = useRef(false);

  // Expose save and clear methods to parent via ref
  useImperativeHandle(ref, () => ({
    save: async () => {
      if (!editorRef.current) throw new Error('Editor not initialized');
      return await editorRef.current.save();
    },
    clear: async () => {
      if (!editorRef.current) throw new Error('Editor not initialized');
      await editorRef.current.clear();
    }
  }));

  useEffect(() => {
    if (!holderRef.current || isInitialized.current) return;

    // Mark as initialized to prevent double initialization
    isInitialized.current = true;

    // Initialize Slabs to get Editor.js tools
    const slabs = new Slabs();
    const tools = slabs.getTools();

    // Initialize Editor.js with Slabs blocks
    const editor = new EditorJS({
      holder: holderRef.current,
      tools: {
        ...tools
      },
      data: data || { blocks: [] },
      onChange: async () => {
        if (onChange) {
          const savedData = await editor.save();
          onChange(savedData);
        }
      },
      placeholder: 'Click + to add a block...',
      inlineToolbar: false
    });

    editorRef.current = editor;

    return () => {
      if (editorRef.current && typeof editorRef.current.destroy === 'function') {
        editorRef.current.destroy();
        editorRef.current = null;
      }
      isInitialized.current = false;
    };
  }, []);

  return <div ref={holderRef} />;
});

// examples/vue/src/components/Editor.vue
<template>
  <div ref="holderRef"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import EditorJS from 'editorjs';
import { Slabs } from '@slabs/client';

interface Props {
  data?: any;
}

interface Emits {
  (e: 'change', data: any): void;
}

const props = defineProps<Props>();
const emit = defineEmits<Emits>();

const holderRef = ref<HTMLDivElement | null>(null);
let editor: EditorJS | null = null;

// Expose save and clear methods
defineExpose({
  async save() {
    if (!editor) throw new Error('Editor not initialized');
    return await editor.save();
  },
  async clear() {
    if (!editor) throw new Error('Editor not initialized');
    await editor.clear();
  }
});

onMounted(() => {
  if (!holderRef.value) return;

  // Initialize Slabs to get Editor.js tools
  const slabs = new Slabs();
  const tools = slabs.getTools();

  // Initialize Editor.js with Slabs blocks
  editor = new EditorJS({
    holder: holderRef.value,
    tools: {
      ...tools
    },
    data: props.data || { blocks: [] },
    onChange: async () => {
      if (editor) {
        const savedData = await editor.save();
        emit('change', savedData);
      }
    },
    placeholder: 'Click + to add a block...',
    inlineToolbar: false
  });
});

onBeforeUnmount(() => {
  if (editor && typeof editor.destroy === 'function') {
    editor.destroy();
    editor = null;
  }
});
</script>
