// examples/vue/src/App.vue
<template>
  <EditorWithControls storage-key="slabs-content" />
</template>

<script setup lang="ts">
/**
 * App - Vue Example using @slabs/editor
 * Icon-only UI with save button, view toggle, notifications, and keyboard shortcuts
 */

import EditorWithControls from './components/EditorWithControls.vue';
</script>

// examples/react/src/App.tsx
/**
 * App - React Example using @slabs/editor
 * Icon-only UI with save button, view toggle, notifications, and keyboard shortcuts
 */

import { EditorWithControls } from './components/EditorWithControls';

function App() {
  return <EditorWithControls storageKey="slabs-content" />;
}

export default App;
