// examples/react/blocks/wysiwyg/render.tsx
import { getField } from '@slabs/helpers';
import type { RenderContext } from '@slabs/renderer';
import './style.css';

interface WysiwygBlockProps {
  data: any;
  context?: RenderContext;
}

export default function WysiwygBlock({ data }: WysiwygBlockProps) {
  const text = getField<string>(data, 'text');

  return (
    <div className="paragraph-block">
      {text && <div dangerouslySetInnerHTML={{ __html: text }} />}
    </div>
  );
}

// examples/vue/blocks/wysiwyg/render.vue
<template>
  <div class="paragraph-block">
    <div v-if="text" v-html="text"></div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { getField } from '@slabs/helpers';
import './style.css';

interface Props {
  data: any;
  context?: any;
}

const props = defineProps<Props>();

const text = computed(() => getField<string>(props.data, 'text'));
</script>
