// examples/vue/src/components/Renderer.vue
<template>
  <div v-if="!data || !data.blocks || data.blocks.length === 0" class="empty-state">
    <h2>No content yet</h2>
    <p>Create some content in the editor first</p>
  </div>
  <div v-else ref="containerRef" class="slabs-content"></div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import { SlabsRenderer } from '@slabs/renderer';

interface Props {
  data?: any;
}

const props = defineProps<Props>();
const containerRef = ref<HTMLDivElement | null>(null);

const renderContent = async () => {
  if (!containerRef.value || !props.data) return;

  // Clear existing content
  containerRef.value.innerHTML = '';

  // Initialize renderer
  const renderer = new SlabsRenderer();

  try {
    // Render the content
    const rendered = await renderer.render(props.data, {
      theme: 'light',
      mode: 'public'
    });
    containerRef.value.appendChild(rendered);
  } catch (error) {
    console.error('Error rendering content:', error);
  }
};

// Watch for data changes
watch(() => props.data, renderContent, { deep: true });

// Render on mount
onMounted(renderContent);
</script>

// examples/react/src/components/Renderer.tsx
import { useEffect, useRef } from 'react';
import { SlabsRenderer } from '@slabs/renderer';

interface RendererProps {
  data?: any;
}

export function Renderer({ data }: RendererProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!containerRef.current || !data) return;

    // Clear existing content
    containerRef.current.innerHTML = '';

    // Initialize renderer
    const renderer = new SlabsRenderer();

    // Render the content
    renderer.render(data, {
      theme: 'light',
      mode: 'public'
    }).then(rendered => {
      containerRef.current?.appendChild(rendered);
    }).catch(error => {
      console.error('Error rendering content:', error);
    });
  }, [data]);

  if (!data || !data.blocks || data.blocks.length === 0) {
    return (
      <div className="empty-state">
        <h2>No content yet</h2>
        <p>Create some content in the editor first</p>
      </div>
    );
  }

  return <div ref={containerRef} className="slabs-content" />;
}
